# Mininet

FROM ubuntu:16.04


MAINTAINER Robert Grzelka <robert.grzelka@outlook.com>
ARG user=robgrzel




RUN apt-get update && \
apt-get install -y --no-install-recommends \
openssh-server cmake gcc build-essential nano vim \
python tcpdump telnet byacc flex iproute2 \
gdbserver less bison valgrind firefox \
curl iproute2 iputils-ping mininet net-tools \
tcpdump x11-xserver-utils xterm



RUN mkdir /var/run/sshd
RUN echo 'root:root' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile


RUN useradd -m -d /home/mininet -s /bin/bash mininet
RUN echo -e '1\n1' | passwd mininet --stdin
RUN adduser mininet sudo
RUN mkdir -p /home/mininet

USER root
WORKDIR /root

ADD entry.sh /

RUN cp -r /bin/ping /sbin/ping \
 && cp -r /bin/ping6 /sbin/ping6 \
 && cp -r /usr/sbin/tcpdump /usr/bin/tcpdump \
 && chmod +x /entry.sh


EXPOSE 22 6633 6653 6640

ENTRYPOINT ["/entry.sh"]

#CMD ["/usr/sbin/sshd", "-D"]
